<!DOCTYPE articles[
<!ELEMENT articles (article+)>
<!ELEMENT article (name,month,author+,(reviews,feedback?)*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT author EMPTY>
<!ELEMENT feedback (#PCDATA)>
<!ELEMENT reviews ANY>

<!ATTLIST article id ID #REQUIRED>
<!ATTLIST author name CDATA #REQUIRED>
<!ATTLIST reviews lang CDATA #IMPLIED>
]>

<articles>
  <article id="x34675">
    <name>Apache Spark Architecture</name>
    <month>december</month>
    <author name="kay vennisla"/>
    <reviews lang=""/>
    <feedback > high rating</feedback>
    <reviews lang="de">The best content with diagrams</reviews>
  </article>
</articles>
