=== galvarez33/FINAL-SW2/Tema_3_JSON/json_schema_node/schemas/movie_schema.json
{
  "$id": "http://example.com/schemas/movie.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "type": "object",
  "title": "movie",
  "description": "Information about a movie",
  "required": ["title", "plot", "year", "country", "runtime", "genres", "rating", "directors", "actors"],
  "properties": {
    "title": {
      "type": "string",
      "description": "Movie's title"
    },
    "year": {
      "type": "number",
      "minimum": 1888 ,
      "description": "Release year"
    },
    "plot": {
      "type": "string",
      "description": "Brief summary of the movie"
    },
    "country": {
      "type": "string",
      "description": "Country of origin"
    },
    "runtime": {
      "type": "number",
      "minimum": 0,
      "description": "Movie's runtime in minutes"
    },
    "genres": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "description": "Movie genre"
      }
    },
    "rating": {
      "enum": ["G", "M", "PG", "R", "X", "Not Rated"],
      "description": "MPAA rating of the movie"
    },
    "directors": {
      "type": "array",
      "description": "Movie directors",
      "minItems": 1,
      "items": { "$ref": "#/$defs/person" }
    },
    "actors": {
      "type": "array",
      "description": "Movie actors",
      "minItems": 1,
      "items": { "$ref": "#/$defs/person" }
    }
  },
  "$defs": {
    "person": {
       "type": "object",
       "description": "Represents a person's information",
       "required": ["name", "age"],
       "properties": {
         "name": {
           "type": "string",
           "description": "Actor's name"
         },
         "age": {
           "type": "number",
           "minimum": 0,
           "description": "Actor's age"
         }
       }
    }
  }
}

=== galvarez33/FINAL-SW2/Tema_3_JSON/json_schema/ejercicio_3.json
{
  "title": "Terrifier 2",
  "year": 2023,
  "plot": "After being resurrected by a sinister entity, Art the Clown returns to the timid town of Miles County where he targets a teenage girl and her younger brother on Halloween night.",
  "country": "United States of America",
  "runtime": 138,
  "genres": ["Horror", "Slasher", "Gore"],
  "rating": "Not Rated",
  "directors": [{
    "name": "Damien Leone",
    "age": 32 
  }],
  "actors": [
    {
      "name": "David Howard Thornton",
      "age": 42
    },
    {
      "name": "Lauren LaVera",
      "age": 28
    },
    {
      "name": "Elliott Fullam",
      "age": 17
    },
    {
      "name": "Sarah Voigt",
      "age": 37
    },
    {
      "name": "Kailey Hyman",
      "age": 27
    },
    {
      "name": "Griffin Santopietro",
      "age": 17
    },
    {
      "name": "Owen Myre",
      "age": 17
    },
    {
      "name": "Casey Hartnett",
      "age": 32
    },
    {
      "name": "Samantha Scaffidi",
      "age": 34
    },
    {
      "name": "Felissa Rose",
      "age": 53
    }
  ]
}
